### ISSUE TITLE
Need Samples Project

### ISSUE THREAD

**Issue by rstanwar** [juhgiyo/EpLibrary#1]
Hi,
Thanks for sharing such a great library but it would be great if you create sample projects in all your open source libraries so that it would be easy for us to integrate it in our systems.

Thanks & Regards

Rstanwar

**Comment by juhgiyo** [comment]
First of all thank you for your interest in EpLibrary.
 However, this is more like my personal projects, which I work on my spare time (and I am the only one who work on it currently). I cannot guarantee you when I will be able to provide you a sample project (since it takes time and effort to create the resourceful sample project, which probably the one you want.) But you might be able to see how I actually linked this library by looking at my other projects in github (EpOraLibrary, or EpServerEngine) since those projects are based on EpLibrary. And you can also check out this project's Wiki page at (https://github.com/juhgiyo/EpLibrary/wiki) for some usage guide of each framework. 
Finally, if you are integrating with your system, I strongly recommend you to read the LICENSE carefully as this project is licensed under GPL v3.0.
Again thank you for your interest, and I am very sorry that I couldn't be more helpful.
